config/routes.rb
Rails.application.routes.draw do
  post 'devices/send_email'
  resources :devices

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :users
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :device
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :account
	has_many :vendors
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:send_email]
  
  def index
    @devices = Device.all
  end

  def show
    @device = Device.find(params[:id])
  end

  def new
  
  end

  def create

  end

  def destroy
  
  end

  def edit

  end

  def send_email
    puts "params value:::::::#{params}"
    puts "coming to send_mail::::::::::::::::"
    EmailNotificationWorker.perform_async()
    render json: {status: "success"}
  end

  def update
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_helper.rb
module DeviceHelper
	
	def temperature_data
		messages = []
		@device.messages.each do |msg| messages<< {temp: msg.temperature, date: msg.polled_at}  end
		messages.to_json
	end

end

app/views/devices/index.html.erb
<h1>Device#index</h1>
<p>Find me in app/views/devices/index.html.erb</p>
<p><%= @devices %></p>


<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Vendor_id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.id %></td>
        <td><%= link_to 'Show', device, method: :get %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_device_path %>

app/views/devices/show.html.erb
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

<%= javascript_tag do %>
  temperature_data = <%= temperature_data.html_safe %>;

  var x_data = [], y_data =[], x_data_2 =[], y_data_2=[]; 
    for (var i = 0; i < temperature_data.length ; i += 1) {
    if(temperature_data.length/2 <= i){
        x_data.push(new Date(temperature_data[i]['date']));
        y_data.push(temperature_data[i]['temp']);
     }
     else{
         x_data_2.push(new Date(temperature_data[i]['date']));
        y_data_2.push(temperature_data[i]['temp']);
     }   
    }
<% end %>  
<script>
</script>

         <div class="flex">

            <header>
             <div class="title">
                 Intlosol
             </div>
            </header>
            
            <div class="middle">
                 <div class="map-data">
                    <div class='map'>
                        <div id="map"></div>
                    </div>
                    <div class='location'>
                        <p class="device_name">
                            ITC0001
                        </p>
                        <p class="device-address">
                            Rajaji,Avenue,Annexe,valasaravakkam,chennai-87
                        </p>
                    </div>
                 </div>
                 <div class="graph-data">
                    <div class="device-stats">
                        <div class="stats-label">
                            <p class="celcius-text">Celcius</p>
                        </div>
                        <div class="max-temp-box">
                            <p class="max-temp-text">Max Temp</p>
                            <p class="max-temp-value">28</p>
                        </div>
                        <div class="min-temp-box">
                            <p class="min-temp-text">Min Temp</p>
                            <p class="min-temp-value">17</p>
                        </div>
                        <div class="mean-temp-box">
                            <p class="mean-temp-text">Mean Temp</p>
                            <p class="mean-temp-value">21</p>
                        </div>
                        <div class="current-temp-box">
                            <p class="current-temp-text">Current Temp</p>
                            <p class="current-temp-value">18</p>
                        </div>
                    </div>
                    <div class="graph-filter">
                        <input class="datefilter" type="text" name="daterange" value="01/08/2016 - 09/30/2016" />
                    </div>
                    <div class="graph">
                        <div id="chart"></div>
                    </div>
                 </div>
                 <div class="recent-data">
                    <div class="customer-credentials">
                        <img class="customer-logo" src="/itc-logo.jpg" alt="itc logo" />
                    </div>
                    <div class="data-list">
                      <label class="recent-records">Recent records</label>
                      <table align="center">
                          <thead>
                            <tr>
                              <th>Temp</th>
                              <th>Date</th>
                            </tr>
                          </thead>

                          <tbody>
                              <tr>
                                <td>24</td>
                                <td>1 minute ago</td>
                              </tr>
                              <tr>
                                <td>22</td>
                                <td>16 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                              <tr>
                                <td>21</td>
                                <td>32 minutes ago</td>
                              </tr>
                          </tbody>
                         </table>  
                    </div>
                 </div>
            </div>
            
            <footer>
             <p>Intlosol LTD, 2016</p>
            </footer>
        
        </div>  

<script>
window.onload = function () {
  x_data.unshift("x")
  y_data.unshift("temp")
  var chart = c3.generate({
    padding: {
        top: 20,
        right: 50,
        bottom: 20,
        left: 50,
    },
    data: {
        x: 'x',
        columns: [x_data, y_data],
        type: 'line'
    },
    color: {
        pattern: ['black']
    },
    axis: {
        x: {
            label: "date",
            type: 'timeseries',
            tick: {
                count: 5,
                format: function (x) { 
                    date = x.getDate()+"-"+ x.getMonth()+"-"+ x.getFullYear()+" "+ x.getHours()+":"+x.getMinutes()+":"+x.getSeconds()
                    console.log(date); 
                    return date; 
                }
            }
        },
        y: {
            label: "temperature"
        }
    },
    zoom: {
        enabled: true
    },
    subchart: {
        show: true
    }
});
        y_data_2.unshift("temp");
        jQuery('.map').on( "click", function(e){
            console.log("coming inside!!!!")
            chart.x(x_data_2);
            chart.load({
                columns: [ y_data_2 ],
                unload: ['temp']
            });
        });
     
     $(function() {
        $('.datefilter').daterangepicker({
            timePicker: true,
            timePickerIncrement: 30,
            locale: {
                format: 'MM/DD/YYYY h:mm A'
            }
        });
    });
}
</script>
<script>
      function initMap() {
        console.log("coming here!!");
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,
          center: {lat: 13.0827, lng: 80.2707}
        });
        var geocoder = new google.maps.Geocoder();

      
          geocodeAddress(geocoder, map);
      
      }

      function geocodeAddress(geocoder, resultsMap) {
        geocoder.geocode({'address': "Rajai, avenue Annexe, valasaravakkam,chennai -87"}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAku0HEpFEy0B1EDoycg7PIvaB0XeS6h0&callback=initMap">
</script>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Tempsense</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdn.pubnub.com/sdk/javascript/pubnub.4.0.10.js"></script>
<script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
<%= javascript_tag do %>
  temperature_data = <%= temperature_data.html_safe %>;

  var x_data = [], y_data =[], x_data_2 =[], y_data_2=[]; 
    for (var i = 0; i < temperature_data.length ; i += 1) {

    console.log(temperature_data[i]['date']);
    console.log(temperature_data[i]['temp']);
     
        x_data.push(new Date(temperature_data[i]['date']));
        y_data.push(temperature_data[i]['temp']);
    }
<% end %>  
<script>
  pubnub = new PubNub({
        subscribeKey : 'sub-c-6dd7c098-7e9b-11e6-9717-0619f8945a4f',
        auth_key : 'Inlosol',
        uuid : "javascript"
      });
       
    pubnub.addListener({
        status: function(statusEvent) {
            if (statusEvent.category === "PNConnectedCategory") {
            }
        },
        message: function(message) {
            temperature_data.push(message.message["temperature"])
            chart.load({
                columns: [
                    temperature_data
                ],
                unload: 'temperature'
            });
            console.log("New Message!!",message.message["temperature"]);
        },
        presence: function(presenceEvent) {

        }
    })      
    pubnub.subscribe({
        channels: ['backfront'] 
    }); 

</script>

<script>
  x_data.unshift("x")
  y_data.unshift("temp")
  var chart = c3.generate({
    padding: {
        top: 40,
        right: 100,
        bottom: 40,
        left: 100,
    },
    data: {
        x: 'x',
        columns: [x_data, y_data],
        type: 'line'
    },
    axis: {
        x: {
            label: "date",
            type: 'timeseries',
            tick: {
                count: 5
            }
        },
        y: {
            label: "temperature"
        }
    },
    zoom: {
        enabled: true
    },
    subchart: {
        show: true
    }

});

</script>
</head>
<body>

<%= yield %>

</body>
</html>